create table if not exists users (
  id bigint generated by default as identity primary key,
  username varchar(100) not null unique,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  enabled boolean not null default false
);

create table if not exists user_roles (
  user_id bigint not null,
  role varchar(50) not null,
  constraint fk_user_roles_user foreign key (user_id) references users(id) on delete cascade,
  constraint uk_user_roles unique (user_id, role)
);

create table if not exists password_reset_tokens (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  user_id bigint not null,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  created_at timestamp with time zone not null,
  constraint fk_reset_user foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_password_reset_tokens_user_id on password_reset_tokens(user_id);

create table if not exists email_verification_tokens (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  user_id bigint not null,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  created_at timestamp with time zone not null,
  constraint fk_verify_user foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_email_verification_tokens_user_id on email_verification_tokens(user_id);
