create table if not exists business_storefronts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  business_type varchar(50) not null,
  slug varchar(63) not null unique,
  name varchar(120) not null,
  description varchar(500),
  logo_url varchar(500),
  banner_url varchar(500),
  data text not null,
  is_active boolean not null default true,
  created_at timestamp,
  updated_at timestamp,
  constraint fk_business_storefronts_user foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_business_storefronts_user_id on business_storefronts(user_id);
create index if not exists idx_business_storefronts_slug_active on business_storefronts(slug, is_active);
