create table if not exists store_products (
  id bigint generated by default as identity primary key,
  storefront_id bigint not null,
  name varchar(200) not null,
  description text,
  price double precision not null,
  stock integer not null default 0,
  is_delisted boolean not null default false,
  media_urls text,
  category varchar(100),
  is_popular boolean default false,
  created_at timestamp,
  updated_at timestamp,
  constraint fk_store_products_storefront foreign key (storefront_id) references business_storefronts(id) on delete cascade
);

create index if not exists idx_store_products_storefront_id on store_products(storefront_id);
