create table if not exists store_orders (
  id bigint generated by default as identity primary key,
  storefront_id bigint not null,
  customer_name varchar(200),
  customer_phone varchar(50),
  customer_email varchar(255),
  order_items text not null,
  subtotal double precision not null,
  vat double precision not null,
  delivery double precision not null,
  total double precision not null,
  status varchar(30) not null default 'PENDING',
  created_at timestamp,
  updated_at timestamp,
  constraint fk_store_orders_storefront foreign key (storefront_id) references business_storefronts(id) on delete cascade
);

create index if not exists idx_store_orders_storefront_id on store_orders(storefront_id);
create index if not exists idx_store_orders_status on store_orders(status);
