create table if not exists store_configs (
  id bigint generated by default as identity primary key,
  storefront_id bigint not null unique,
  vat_rate double precision not null default 0.075,
  delivery_fee double precision not null default 2000,
  created_at timestamp,
  updated_at timestamp,
  constraint fk_store_configs_storefront foreign key (storefront_id) references business_storefronts(id) on delete cascade
);
