create table if not exists email_otp_codes (
  id bigint generated by default as identity primary key,
  otp_hash varchar(64) not null,
  user_id bigint not null,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  created_at timestamp with time zone not null,
  constraint fk_otp_user foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_email_otp_codes_user_id on email_otp_codes(user_id);
create index if not exists idx_email_otp_codes_hash on email_otp_codes(otp_hash);
